version: '3'
services:
    discovery-service:
        container_name: discovery-service
        build:
            context: discovery-service
            dockerfile: Dockerfile
        image: discovery-service:latest
        ports:
            - "8761:8761"
        networks:
            - restaurante-network
    gateway-service:
        container_name: gateway-service
        build:
            context: gateway-service
            dockerfile: Dockerfile
        image: gateway-service:latest
        ports:
            - "8080:8080"
        networks:
            - restaurante-network
networks:
    restaurante-network:
        driver: bridge